var models = [
    "evasasha",
    "july_koss",
    "_milkyway",
    "mango_shake",
    "lilly_vanilla",
    "candysfox",
    "yournaughtymiss",
    "annie_sweetyxx",
    "cogitademe",
    "lovely_aria",
    "alice_kosmos",
    "lola_bunny94",
    "juicekatee",
    "anna_sabotage",
    "thepleasureofsex",
    "sweet__sugar",
    "wild_schoolgirl",
    "lolla_molla",
    "hell_lo",
    "hayle_green",
    "_woweva__",
    "catanddickxxx",
    "jessica_jonses",
    "vivian_clark",
    "kinkyali",
    "feelmemore",
    "_virtual_lady_",
    "little_vee",
    "xllodaz",
    "blackmango_mary",
    "tiffanyhouston_",
    "marylanex",
    "liisppb",
    "sweet_tinker_bell",
    "agatha137",
    "evelissa",
    "kleasure",
    "bettybonhill",
    "alicewood_",
    "amazon_girl",
    "melisasweety",
    "funnysimka",
    "qeensgambit",
    "angelinamoore",
    "rennatha21",
    "tonibrock",
    "selfish_ashley",
    "_love_daddys",
    "amazing_roxana",
    "ms_seductive",
    "miley_k18"
];

function shuffleModels() {
    for (let i = models.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [models[i], models[j]] = [models[j], models[i]];
    }
}
